version: "3.8"
services:
  algod:
    build: .
    image: ghcr.io/voinetwork/docker-participation-node:latest
    volumes:
      - /var/lib/voi/algod/data:/algod/data/:rw
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  shepherd:
    build: .
    image: containrrr/shepherd
    environment:
      RUN_ONCE_AND_EXIT: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 0
      restart_policy:
        condition: none
      labels:
        - swarm.cronjob.enable=true
        - swarm.cronjob.schedule=0 0 * * *
        - swarm.cronjob.skip-running=true
      placement:
        constraints:
          - node.role == manager
  scheduler:
    image: crazymax/swarm-cronjob:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - "TZ=Europe/London"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager